### ISSUE TITLE
whitelist word

### ISSUE THREAD

**Issue by bazir123** [ocecer/telegram-to-telegram-message-forwarder#1]
hello
will you please add whitelist word?
thanks

**Comment by ocecer** [comment]
Hi, what do you mean with whitelist words? If it is not blacklisted, it is allowed anyways. How do you want to use the whitelist words?

**Comment by bazir123** [comment]
example i define word1 word2 word3 then if this word is in messages, script forward it.
also how is checking message? i mean i want set script to read, unread message of source channel or begin check and forward message  from past 8 hour.

**Comment by ocecer** [comment]
Cool, I can add whitelisting function in first convinent time. But the other one can be new script in the future

**Comment by ocecer** [comment]
i added whitelisting function as "FORWARD_IF_MESSAGE_CONSIST_WORDS"
